### 1. Login
# @name loginRequest
POST https://toughquilt.backendless.app/api/users/login
Content-Type: application/json

{
  "login": "testtest@example.com",
  "password": "password123"
}


### 2. Start a Chat Thread
# @name startChatRequest
POST http://127.0.0.1:5000/start_chat
user-token: {{loginRequest.response.headers.user-token}}
Content-Type: application/json

{
  "objectId": "{{loginRequest.response.body.objectId}}"
}


### 3. Ask a Question 
POST http://127.0.0.1:5000/ask
user-token: {{loginRequest.response.headers.user-token}}
Content-Type: application/json

{
  "prompt": "In one sentence, what is the purpose of the Federal Acquisition Regulation?",
  "thread_id": "{{startChatRequest.response.body.thread_id}}",
  "objectId": "{{loginRequest.response.body.objectId}}"
}